### ISSUE TITLE
Items detected but not imported

### ISSUE THREAD

**Issue by lahbibe** [ksainc/integration_ews#28]
Hello,

After filling in the required information, when i press the "Connect" button. The app will then attempt an initial connection to the remote system is successful, it retrieve a list of all available calendars and contacts folders from the remote system (see following screenshot) but it's impossible to "import them" on calendar, todo nor contacts in our nexcloud (version 27.1.5 Enterprise)

We don't have errors without this one "Failed to load remote collections list: "Remote Error: ErrorNoPublicFolderReplicaAvailable - There are no public folder servers available."

![image](https://github.com/ksainc/integration_ews/assets/154585994/e9250984-c0e3-4e1e-bd65-eb1cd6c55576)

How can we debug the problem please.

**Comment by ksainc** [comment]
Morning,

It seems to be failing when trying to pull a list of Public folders. 

Which version of Exchange are you using?

Sebastian

**Comment by ksainc** [comment]
I've released a patch that should fix your issue. It should be on the app store in about an hour.

Let me know the result please.

**Comment by lahbibe** [comment]
![image](https://github.com/ksainc/integration_ews/assets/154585994/aa7cad06-abb1-477e-86cb-b312f052a90f)

**Comment by ksainc** [comment]
Hi @lahbibe 

This is not a issue with the app, this is a issue with NextCloud. NC does not support HTML descriptions, and Exchange saves everything in 

See issue https://github.com/nextcloud/calendar/issues/5636

But I do have an idea for a work around, I'll have it implemented soon, since I've had so many people ask about it.

Sebastian
